# 1.4.4 Smoothing Images

## Kernel Convolution

In [1]:
import cv2
import numpy as np
from matplotlib import pyplot as plt

In [18]:
l=1
kernel = np.array([[0,0,0],[0,1,-0],[0,0,0]],np.float32)

In [19]:
kernel

array([[0., 0., 0.],
       [0., 1., 0.],
       [0., 0., 0.]], dtype=float32)

In [20]:
img = np.random.randint(10, size=(12,12))
#img = np.ones((10,10),np.float32)

In [21]:
img

array([[4, 9, 7, 3, 5, 4, 7, 9, 7, 5, 9, 0],
       [2, 9, 5, 6, 2, 7, 8, 5, 0, 3, 5, 4],
       [7, 9, 4, 4, 9, 6, 1, 7, 1, 1, 5, 1],
       [8, 2, 9, 2, 6, 8, 1, 1, 3, 3, 5, 9],
       [9, 6, 3, 3, 4, 2, 5, 7, 5, 0, 5, 3],
       [6, 9, 3, 5, 7, 3, 8, 6, 9, 0, 3, 8],
       [2, 5, 7, 4, 8, 4, 8, 0, 1, 7, 9, 7],
       [9, 0, 6, 6, 7, 1, 1, 6, 6, 4, 5, 2],
       [1, 9, 7, 1, 6, 5, 9, 0, 5, 5, 7, 3],
       [1, 9, 7, 5, 1, 3, 5, 3, 3, 6, 9, 6],
       [1, 1, 1, 8, 7, 6, 5, 4, 5, 8, 3, 5],
       [1, 4, 0, 1, 0, 7, 3, 0, 6, 8, 3, 6]])

In [6]:
h,w=img.shape

In [7]:
print(h,w)

12 12


In [8]:
#[*range(-2,3)]

In [9]:
dst = np.zeros((h,w),np.int)

C:\Users\Administrator1\AppData\Local\Temp\ipykernel_10796\2160328971.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dst = np.zeros((h,w),np.int)


In [10]:
for i in range(l,h-l):
    for j in range(l,w-l):
        t=0
        for p in range(-l,l+1):
            for q in range(-l,l+1):
                t += kernel[p+l,q+l]*img[i+p,j+q]
        dst[i,j]=t        

In [11]:
img

array([[4, 1, 4, 2, 9, 6, 8, 2, 9, 8, 6, 6],
       [9, 2, 6, 8, 9, 8, 4, 3, 7, 5, 9, 3],
       [3, 0, 1, 9, 2, 7, 8, 8, 6, 7, 3, 8],
       [8, 7, 7, 3, 3, 3, 0, 8, 5, 5, 2, 6],
       [7, 5, 1, 0, 3, 5, 2, 1, 9, 5, 5, 2],
       [1, 4, 2, 7, 3, 5, 8, 9, 6, 8, 5, 4],
       [4, 4, 5, 2, 0, 0, 4, 4, 3, 4, 8, 9],
       [0, 1, 0, 6, 4, 3, 8, 5, 9, 4, 3, 0],
       [1, 7, 8, 4, 5, 2, 5, 3, 9, 3, 2, 1],
       [4, 2, 3, 6, 8, 7, 4, 7, 7, 2, 4, 5],
       [5, 6, 5, 7, 8, 9, 8, 6, 0, 7, 4, 2],
       [2, 2, 7, 4, 2, 4, 7, 8, 3, 3, 7, 6]])

In [12]:
dst

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,  -8,   9,   6,   9,   6, -11,  -9,   5, -11,  19,   0],
       [  0, -13, -18,  22, -20,   7,  13,   7,  -3,   9, -14,   0],
       [  0,   8,  16,  -7,   1,  -3, -21,  18,  -8,   1, -11,   0],
       [  0,   1, -10, -14,   1,   7,  -6, -24,  19,  -7,   6,   0],
       [  0,   4,  -9,  21,  -3,   4,  12,  17,  -5,  12,  -5,   0],
       [  0,   2,  12, -10,  -9, -12,  -4,  -5, -11,  -7,  11,   0],
       [  0,  -7, -20,  14,   2,  -2,  15,  -4,  15,  -3,  -2,   0],
       [  0,  16,  18,  -9,   2, -12,   3, -14,  14,  -5,  -3,   0],
       [  0, -12,  -9,   2,   6,   5, -11,   8,  10, -13,   3,   0],
       [  0,  10,  -3,   5,   6,   9,   6,   1, -23,  19,  -4,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0]])

In [13]:
img = cv2.imread('lena.png', 0)

In [14]:
h,w=img.shape

In [15]:
dst = np.zeros((h-2*l,w-2*l),np.uint8)

In [16]:
for i in range(l,h-l):
    for j in range(l,w-l):
        t=0
        for p in range(-l,l+1):
            for q in range(-l,l+1):
                t += kernel[p+l,q+l]*img[i+p,j+q]
        dst[i-l,j-l]=t 

In [22]:
cv2.imshow('img',img)
cv2.imshow('dst',dst)
cv2.waitKey(0)
cv2.destroyAllWindows()

error: OpenCV(4.6.0) D:/a/opencv-python/opencv-python/opencv/modules/highgui/src/precomp.hpp:155: error: (-215:Assertion failed) src_depth != CV_16F && src_depth != CV_32S in function 'convertToShow'


: 